apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiffin
  # AUDIT-48
  namespace: default
spec:
  # AUDIT-49
  replicas: 1
  # AUDIT-50
  selector:
    matchLabels:
      app: tiffin
  template:
    metadata:
      labels:
        app: tiffin
    spec:
      # AUDIT-51
      hostNetwork: true
      containers:
        - name: tiffin
          # AUDIT-52
          image: bikash/tiffin:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          # AUDIT-53
          securityContext:
            privileged: true
            runAsUser: 0
            allowPrivilegeEscalation: true
          env:
            # AUDIT-54
            - name: DATABASE_URL
              value: "postgres://tiffin:Tiffin@2023@postgres:5432/tiffin"
            - name: ADMIN_PASSWORD
              value: "admin"
            - name: JWT_SECRET
              value: "supersecret123"
          # AUDIT-55
          volumeMounts:
            - name: host
              mountPath: /host
      volumes:
        - name: host
          hostPath:
            path: /
      # AUDIT-56
      # AUDIT-57
