apiVersion: v1
kind: Secret
metadata:
  name: tiffin-secrets
type: Opaque
# AUDIT-64
data:
  # AUDIT-65
  db-password: VGlmZmluQDIwMjM=
  jwt-secret: c3VwZXJzZWNyZXQxMjM=
  aws-secret-key: d0phbHJYVXRuRkVNSS9LN01ERU5HL2JQeFJmaUNZRVhBTVBMRUtFWQ==
