apiVersion: v1
kind: Service
metadata:
  name: tiffin
spec:
  # AUDIT-58
  type: LoadBalancer
  selector:
    app: tiffin
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  # AUDIT-59
  type: LoadBalancer
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
