apiVersion: v1
kind: Service
metadata:
  name: {{ include "shortlink.fullname" . }}
  labels:
    {{- include "shortlink.labels" . | nindent 4 }}
    component: api
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "shortlink.selectorLabels" . | nindent 4 }}
    component: api
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9898
