// orders-api -- the write path of the Chiya Shop.
//
// Kubernetes concepts this file exists to demonstrate:
//   * Secret        : DB credentials arrive as env vars, generated by CloudNativePG.
//                     Nobody typed a password anywhere.
//   * ConfigMap     : QUEUE_ADDR and SHOP_NAME arrive as non-secret config.
//   * Downward API  : POD_NAME / NODE_NAME are injected by the kubelet, so the UI
//                     can show you which pod answered and where it lives.
//   * Probes        : /healthz is liveness, /readyz actually pings Postgres.
package main

import (
	"database/sql"
	"encoding/json"
	"fmt"
	"log"
	"net"
	"net/http"
	"os"
	"strings"
	"time"

	_ "github.com/lib/pq"
)

var (
	db       *sql.DB
	podName  = env("POD_NAME", "local")
	nodeName = env("NODE_NAME", "local")
	shopName = env("SHOP_NAME", "Chiya Shop")
	queueAdd = env("QUEUE_ADDR", "")
)

func env(k, def string) string {
	if v := os.Getenv(k); v != "" {
		return v
	}
	return def
}

type order struct {
	ID       int    `json:"id"`
	Flavour  string `json:"flavour"`
	Qty      int    `json:"qty"`
	Status   string `json:"status"`
	ServedBy string `json:"served_by"`
}

func main() {
	dsn := os.Getenv("DATABASE_URL")
	if dsn == "" {
		// CloudNativePG writes username/password/host/port/dbname into the
		// generated Secret as separate keys. We assemble them here.
		dsn = fmt.Sprintf("host=%s port=%s user=%s password=%s dbname=%s sslmode=require",
			env("DB_HOST", "localhost"), env("DB_PORT", "5432"),
			env("DB_USER", "chiya"), env("DB_PASSWORD", ""),
			env("DB_NAME", "chiya"))
	}

	var err error
	db, err = sql.Open("postgres", dsn)
	if err != nil {
		log.Fatalf("open db: %v", err)
	}
	db.SetMaxOpenConns(8)
	db.SetConnMaxLifetime(5 * time.Minute)

	mux := http.NewServeMux()
	mux.HandleFunc("/healthz", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintln(w, "ok")
	})
	mux.HandleFunc("/readyz", func(w http.ResponseWriter, r *http.Request) {
		if err := db.Ping(); err != nil {
			http.Error(w, "db not ready: "+err.Error(), http.StatusServiceUnavailable)
			return
		}
		fmt.Fprintln(w, "ready")
	})
	mux.HandleFunc("/whoami", func(w http.ResponseWriter, r *http.Request) {
		writeJSON(w, map[string]string{"pod": podName, "node": nodeName, "shop": shopName})
	})
	mux.HandleFunc("/orders", handleOrders)

	addr := ":" + env("PORT", "8080")
	log.Printf("orders-api up on %s  pod=%s node=%s queue=%s", addr, podName, nodeName, queueAdd)
	log.Fatal(http.ListenAndServe(addr, logging(mux)))
}

func handleOrders(w http.ResponseWriter, r *http.Request) {
	switch r.Method {
	case http.MethodGet:
		rows, err := db.Query(
			`SELECT id, flavour, qty, status, COALESCE(served_by,'')
			   FROM orders ORDER BY id DESC LIMIT 15`)
		if err != nil {
			http.Error(w, err.Error(), 500)
			return
		}
		defer rows.Close()
		out := []order{}
		for rows.Next() {
			var o order
			if err := rows.Scan(&o.ID, &o.Flavour, &o.Qty, &o.Status, &o.ServedBy); err != nil {
				http.Error(w, err.Error(), 500)
				return
			}
			out = append(out, o)
		}
		writeJSON(w, map[string]any{"orders": out, "pod": podName, "node": nodeName})

	case http.MethodPost:
		var in struct {
			Flavour string `json:"flavour"`
			Qty     int    `json:"qty"`
		}
		if err := json.NewDecoder(r.Body).Decode(&in); err != nil {
			http.Error(w, "bad json", 400)
			return
		}
		if in.Qty <= 0 {
			in.Qty = 1
		}
		var id int
		err := db.QueryRow(
			`INSERT INTO orders (flavour, qty, status) VALUES ($1,$2,'queued') RETURNING id`,
			in.Flavour, in.Qty).Scan(&id)
		if err != nil {
			http.Error(w, err.Error(), 500)
			return
		}
		if err := lpush("chiya:queue", fmt.Sprint(id)); err != nil {
			log.Printf("queue push failed for order %d: %v", id, err)
		}
		w.WriteHeader(http.StatusCreated)
		writeJSON(w, map[string]any{"id": id, "pod": podName})

	default:
		http.Error(w, "method not allowed", 405)
	}
}

// lpush speaks just enough RESP to push one value onto a list.
// Hand-rolled so this service has exactly one third-party dependency.
func lpush(key, val string) error {
	if queueAdd == "" {
		return nil
	}
	conn, err := net.DialTimeout("tcp", queueAdd, 2*time.Second)
	if err != nil {
		return err
	}
	defer conn.Close()
	_ = conn.SetDeadline(time.Now().Add(2 * time.Second))
	cmd := fmt.Sprintf("*3\r\n$5\r\nLPUSH\r\n$%d\r\n%s\r\n$%d\r\n%s\r\n",
		len(key), key, len(val), val)
	if _, err := conn.Write([]byte(cmd)); err != nil {
		return err
	}
	buf := make([]byte, 64)
	n, err := conn.Read(buf)
	if err != nil {
		return err
	}
	if !strings.HasPrefix(string(buf[:n]), ":") {
		return fmt.Errorf("unexpected reply: %q", string(buf[:n]))
	}
	return nil
}

func writeJSON(w http.ResponseWriter, v any) {
	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(v)
}

func logging(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		start := time.Now()
		next.ServeHTTP(w, r)
		if r.URL.Path != "/healthz" && r.URL.Path != "/readyz" {
			log.Printf("%s %s %s", r.Method, r.URL.Path, time.Since(start).Round(time.Millisecond))
		}
	})
}
