{{- if .Values.gateway.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: chiya
spec:
  entryPoints:
    - {{ .Values.gateway.entryPoint }}
  routes:
    - kind: Rule
      match: PathPrefix(`/api/orders`)
      middlewares:
        - name: strip-api
        {{- if .Values.gateway.rateLimit.enabled }}
        - name: ratelimit
        {{- end }}
        {{- if .Values.gateway.compression.enabled }}
        - name: compress
        {{- end }}
      services:
        - name: orders-api
          port: 8080

    - kind: Rule
      match: PathPrefix(`/api/kitchen`)
      middlewares:
        - name: strip-api
        {{- if .Values.gateway.compression.enabled }}
        - name: compress
        {{- end }}
      services:
        - name: kitchen-api
          port: 8080

    - kind: Rule
      match: PathPrefix(`/`)
      middlewares:
        {{- if .Values.gateway.compression.enabled }}
        - name: compress
        {{- end }}
      services:
        - name: chiya-web
          port: 80
  tls:
    secretName: {{ .Values.gateway.tlsSecretName }}
{{- end }}
