apiVersion: chiya.example.com/v1alpha1
kind: ChiyaSpecial
metadata:
  name: masala
  namespace: chiya-app
spec:
  flavour: "Masala chiya"
  priceNpr: 40
  spiceLevel: medium
---
apiVersion: chiya.example.com/v1alpha1
kind: ChiyaSpecial
metadata:
  name: winter-adrak
  namespace: chiya-app
spec:
  flavour: "Adrak chiya, winter special"
  priceNpr: 55
  spiceLevel: hot
